// react-crud-users/src/Components/User/CreateComponent.js
import React from 'react';
import { Button, Form, FormGroup, Label, Input } from 'reactstrap';
import User from '../../../services/userService';

class CreateComponent extends React.Component {
  state = {
    id: 0,
    name: '',
    email: '',
    submitted = false
  }


  /*
    user: User = new User();
    submitted = false;
  
    constructor(private userService: UserService, private router: Router) { }
  
    ngOnInit() {
    }
  
    newUser(): void {
      this.submitted = false;
      this.user = new User();
    }*/


  /*componentDidMount() {
    // if item exists, populate the state with proper data
    if (this.props.item) {
      const { id, name, email } = this.props.item
      this.setState({ id, name, email })
    }
  }*/


  onChange = e => {
    this.setState({ [e.target.name]: e.target.value })
  }


  save = e => {
    e.preventDefault();

    User.createUser(this.state).then(result => {
      //this.props.setIsRegister(true);
    })
      .catch(error => {
        /*const data = error.response.data;
        let message = [];
  
        for (var key in data.params) {
          message.push(data.params[key].join(', '));
        }
  
        this.setState({
          error: message.join(' \n')
        });*/

      })
  }

  onSubmit() {
    submitted = true;
    this.setState({ submitted })
    this.save();
  }

  gotoList() {
    // this.router.navigate(['/users']);
  }

  render() {
    return (
      <div>
        <h3>Crear usuário</h3>
        <div hidden={this.state.submitted} style="width: 400px;">
          <form onSubmit={this.onSubmit}>
            <div class="form-group">
              <label for="name">Nome</label>
              <input type="text" class="form-control" id="name" required onChange={this.onChange}
                value={this.state.name === null ? '' : this.state.name} name="name" />
            </div>

            <div class="form-group">
              <label for="name">E-mail</label>
              <input type="email" class="form-control" id="email" required onChange={this.onChange}
                value={this.state.email === null ? '' : this.state.email} name="email" />
            </div>

            <button type="submit" class="btn btn-success">Submit</button>
          </form>
        </div>

        <div hidden={this.state.submitted}>
          <h4>Enviado com sucesso!</h4>
        </div>
      </div>
    );
  }
}

export default CreateComponent;

// angular-crud-users/src/app/components/user/create/create.component.ts
import { UserService } from '../../../services/user/user.service';
import { User } from '../../../models/user/user';
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-create',
  templateUrl: './create.component.html',
  styleUrls: ['./create.component.css']
})
export class CreateComponent implements OnInit {

  user: User = new User();
  submitted = false;

  constructor(private userService: UserService, private router: Router) { }

  ngOnInit() {
  }

  newUser(): void {
    this.submitted = false;
    this.user = new User();
  }

  save() {
    this.userService.createUser(this.user)
      .subscribe(data => console.log(data), error => console.log(error));
    this.user = new User();
    this.gotoList();
  }

  onSubmit() {
    this.submitted = true;
    this.save();
  }

  gotoList() {
    this.router.navigate(['/users']);
  }
}

<h3>Crear usuário</h3>
<div [hidden]="submitted" style="width: 400px;">
  <form (ngSubmit)="onSubmit()">
    <div class="form-group">
      <label for="name">Nome</label>
      <input type="text" class="form-control" id="name" required [(ngModel)]="user.name" name="name">
    </div>

    <div class="form-group">
      <label for="name">E-mail</label>
      <input type="email" class="form-control" id="email" required [(ngModel)]="user.email" name="email">
    </div>

    <button type="submit" class="btn btn-success">Submit</button>
  </form>
</div>

<div [hidden]="!submitted">
  <h4>Enviado com sucesso!</h4>
  <!-- <button class="btn btn-success" (click)="newEmployee()">Add</button> -->
</div>
